### ISSUE TITLE
error when loading

### ISSUE THREAD

**Issue by adrian-rt** [bruce30262/TWindbg#15] opened 2021-08-25 15:54 UTC
0:000> .load pykd
0:000> !py -g winext\TWindbg\TWindbg\TWindbg.py

Traceback (most recent call last):

  File "C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\winext\TWindbg\TWindbg\TWindbg.py", line 10, in <module>
    context.init_arch()

  File "C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\winext\TWindbg\TWindbg\context.py", line 17, in init_arch
    cpu_mode = pykd.getCPUMode()

AttributeError: 'module' object has no attribute 'getCPUMode'

**Comment by adrian-rt** [comment] 2021-08-30 17:54
* python 2.7
* 2.0.25
* yes, 32 bit python and 32 bit pykd

**Comment by bruce30262** [comment] 2021-08-31 04:38
So first of all there's no `2.0.25` version in pykd, the latest version is `0.3.4.15`. You can check the version by entering `!pip list` in Windbg after loading pykd.  

Also I did some testing in python 2.7 and it seems that there's some bug in pykd for python 2.7. In my case, TWindbg loaded successfully after the `!py -g winext\TWindbg\TWindbg\TWindbg.py` command, but somehow crashes pykd during further usage:

```
c0000005 Exception in debugger client IDebugEventCallbacks::ChangeEngineState callback.
      PC: 7c4ef123  VA: 0000000c  R/W: 1  Parameter: 00000000
```

After that I also got the "'module' object has no attribute...." error message as you did.  All of this happened in python 2.7, but not in python 3 ( version 3.8 in my case ).

Although I couldn't find the root cause, however I believe the problem came from pykd, not TWindbg, thus I **strongly suggest that you move to python 3 instead of using python 2.7**, since 2.7 has reached its EOL and the pykd develop team is probably gonna focus on developing pykd for python3 instead of 2.7. **I'm also gonna drop the support for python 2.7 now**, since I don't think it's worth spending time on supporting an EOL language in a small, amateur project.

Due to the above, I'm closing this issue. Thanks for reporting though, it make me aware of the issue in python 2.7 and decided to finally drop the support of the language.

**Closed by bruce30262** 2021-08-31 04:38 UTC

**Comment by adrian-rt** [comment] 2021-08-31 18:25
I migrated to 3.8 and it works now.
I had a dependency on 2.7, that's why I was still holding onto that version......

ps: indeed I also got that exception at some point.
